- name: Create .kalite directory
  file: path=/mnt/storage/.kalite state=directory

- name: Create symlink for .kalite directory
  file: src=/mnt/storage/.kalite dest=/root/.kalite state=link

- name: Create .usrsharekalite directory
  file: path=/mnt/storage/.usrsharekalite state=directory

- name: Create symlink for .usrsharekalite directory
  file: src=/mnt/storage/.usrsharekalite dest=/usr/share/kalite state=link

- name: Moving content directory
  shell: mv /mnt/storage/materials/content /mnt/storage/.kalite/content
  args:
    creates: /mnt/storage/.kalite/content

- name: Untar ka-lite sdist
  unarchive: src=/mnt/storage/materials/ka-lite-static-0.16.b2.tar.gz dest=/mnt/storage copy=no

- name: Installing ka-lite
  shell: python setup.py install chdir=/mnt/storage/ka-lite-static-0.16.b2

- name: Creating database directory
  file: path=/mnt/storage/.kalite/database state=directory

- name: Copying over content database
  shell: mv /mnt/storage/materials/content_khan_en.sqlite /mnt/storage/.kalite/database/content_khan_en.sqlite

- name: change setup.py file
  lineinfile: dest=/mnt/storage/ka-lite-static-0.16.b2/{{ item }} regexp='^(\s*)call_command\("annotate_content_items"\)' line="\1pass" backrefs=yes
  with_items:
    - kalite/contentload/management/commands/unpack_assessment_zip.py
    - kalite/distributed/management/commands/setup.py

- name: Setup
  shell: PYTHONPATH=/mnt/storage/ka-lite-static-0.16.b2/dist-packages python kalitectl.py manage setup --noinput --no-assessment-items chdir=/mnt/storage/ka-lite-static-0.16.b2

#- name: Unpacking assessment items
#  shell: PYTHONPATH=/mnt/storage/ka-lite-static-0.16.b2/dist-packages python kalitectl.py manage unpack_assessment_zip /mnt/storage/materials/khan_assessment.zip chdir=/mnt/storage/ka-lite-static-0.16.b2
#  ignore_errors: True
