- name: Checking if ka-lite is on the target
  shell: PYTHONPATH=/mnt/storage/{{ kalite_version.stdout.strip() }}/dist-packages python /mnt/storage/{{ kalite_version.stdout.strip() }}/kalitectl.py 
  register: kalite_test
  ignore_errors: True

- name: Checking if content database is in correct place
  raw: ls /mnt/storage/.kalite/database/content_khan_en.sqlite
  register: content_database_test
  ignore_errors: True

- name: Checking for assessment items
  raw: du -sh /mnt/storage/.kalite/content/assessment/khan/
  register: assessment_test
  ignore_errors: True

# - debug: var=content_database_test
# - debug: var=assessment_test

- name: Installing ka-lite
  include: install_kalite.yml
  when: (content_database_test.stdout.find('No such file') != -1) or
        (assessment_test.stdout.find('6.5G') == -1)
