- name: Checking if ka-lite is on the target
  shell: PYTHONPATH=/mnt/storage/{{ kalite_version.stdout.strip() }}/dist-packages python /mnt/storage/{{ kalite_version.stdout.strip() }}/kalitectl.py 
  register: kalite_test
  ignore_errors: True

- name: Installing ka-lite
  include: install_kalite.yml
  when: hostvars.sandisk.kalite_test.stderr.find('Usage') == -1
